This is a 5 by 5 grid game, AI movement follows our conjecture of 0 strategy. I can play against it, 1 goes first.

In [7]:
import numpy as np

class StrategicGame5x5:
    def __init__(self):
        self.board = np.full((5, 5), None)  # Initialize a 5x5 board with None
        self.player_turn = True  # Start with player's turn

    def display_board(self):
        print(self.board)

    def make_move(self, row, col, player):
        if self.board[row][col] is None:  # Check if the cell is empty
            self.board[row][col] = player
            return True
        return False
    
    def check_full(self):
        return not np.any(self.board == None)  # Check if there's any None left in the board
    
    def calculate_determinant(self):
        # Convert the board to numerical values for determinant calculation
        numeric_board = np.where(self.board == None, 0, self.board).astype(int)
        return np.linalg.det(numeric_board)

    def player_move(self):
        valid_move = False
        while not valid_move:
            try:
                row = int(input("Enter row (0 to 4): "))
                col = int(input("Enter column (0 to 4): "))
                if row < 0 or row > 4 or col < 0 or col > 4:
                    print("Invalid input. Please enter numbers between 0 and 4.")
                else:
                    valid_move = self.make_move(row, col, 1)  # Player is 1
                    if not valid_move:
                        print("This cell is already taken. Try a different cell.")
            except ValueError:
                print("Please enter valid integer numbers.")
    
    def ai_move(self):
        # Implementing the strategy for AI move
        for i in range(5):
            for j in range(5):
                if self.board[i][j] == 1:  # Find where player placed 1
                    if j == 0:  # If 1 is in column 0, place 0 in column 1
                        if self.make_move(i, 1, 0):
                            return
                    elif j == 1:  # If 1 is in column 1, place 0 in column 0
                        if self.make_move(i, 0, 0):
                            return
                    elif j == 2:  # If 1 is in column 2, place 0 in column 3
                        if self.make_move(i, 3, 0):
                            return
                    elif j == 3:  # If 1 is in column 3, place 0 in column 2
                        if self.make_move(i, 2, 0):
                            return
        # If no move has been made following the strategy, just place 0 in the first empty cell
        for i in range(5):
            for j in range(5):
                if self.board[i][j] is None:
                    self.make_move(i, j, 0)
                    return

    def play(self):
        while not self.check_full():
            self.display_board()
            if self.player_turn:
                self.player_move()
            else:
                self.ai_move()
            self.player_turn = not self.player_turn
        
        # Check the determinant to decide the winner
        self.display_board()
        det = self.calculate_determinant()
        if det == 0:
            print("Determinant is 0: 0 wins!")
        else:
            print("Determinant is not 0: 1 wins!")


game = StrategicGame5x5()
game.play()


[[None None None None None]
 [None None None None None]
 [None None None None None]
 [None None None None None]
 [None None None None None]]


Enter row (0 to 4):  0
Enter column (0 to 4):  0


[[1 None None None None]
 [None None None None None]
 [None None None None None]
 [None None None None None]
 [None None None None None]]
[[1 0 None None None]
 [None None None None None]
 [None None None None None]
 [None None None None None]
 [None None None None None]]


Enter row (0 to 4):  1
Enter column (0 to 4):  1


[[1 0 None None None]
 [None 1 None None None]
 [None None None None None]
 [None None None None None]
 [None None None None None]]
[[1 0 None None None]
 [0 1 None None None]
 [None None None None None]
 [None None None None None]
 [None None None None None]]


Enter row (0 to 4):  2
Enter column (0 to 4):  1


[[1 0 None None None]
 [0 1 None None None]
 [None 1 None None None]
 [None None None None None]
 [None None None None None]]
[[1 0 None None None]
 [0 1 None None None]
 [0 1 None None None]
 [None None None None None]
 [None None None None None]]


Enter row (0 to 4):  3
Enter column (0 to 4):  3


[[1 0 None None None]
 [0 1 None None None]
 [0 1 None None None]
 [None None None 1 None]
 [None None None None None]]
[[1 0 None None None]
 [0 1 None None None]
 [0 1 None None None]
 [None None 0 1 None]
 [None None None None None]]


Enter row (0 to 4):  4
Enter column (0 to 4):  4


[[1 0 None None None]
 [0 1 None None None]
 [0 1 None None None]
 [None None 0 1 None]
 [None None None None 1]]
[[1 0 0 None None]
 [0 1 None None None]
 [0 1 None None None]
 [None None 0 1 None]
 [None None None None 1]]


Enter row (0 to 4):  3
Enter column (0 to 4):  4


[[1 0 0 None None]
 [0 1 None None None]
 [0 1 None None None]
 [None None 0 1 1]
 [None None None None 1]]
[[1 0 0 0 None]
 [0 1 None None None]
 [0 1 None None None]
 [None None 0 1 1]
 [None None None None 1]]


Enter row (0 to 4):  2
Enter column (0 to 4):  4


[[1 0 0 0 None]
 [0 1 None None None]
 [0 1 None None 1]
 [None None 0 1 1]
 [None None None None 1]]
[[1 0 0 0 0]
 [0 1 None None None]
 [0 1 None None 1]
 [None None 0 1 1]
 [None None None None 1]]


Enter row (0 to 4):  1
Enter column (0 to 4):  4


[[1 0 0 0 0]
 [0 1 None None 1]
 [0 1 None None 1]
 [None None 0 1 1]
 [None None None None 1]]
[[1 0 0 0 0]
 [0 1 0 None 1]
 [0 1 None None 1]
 [None None 0 1 1]
 [None None None None 1]]


Enter row (0 to 4):  4
Enter column (0 to 4):  1


[[1 0 0 0 0]
 [0 1 0 None 1]
 [0 1 None None 1]
 [None None 0 1 1]
 [None 1 None None 1]]
[[1 0 0 0 0]
 [0 1 0 None 1]
 [0 1 None None 1]
 [None None 0 1 1]
 [0 1 None None 1]]


Enter row (0 to 4):  4
Enter column (0 to 4):  3


[[1 0 0 0 0]
 [0 1 0 None 1]
 [0 1 None None 1]
 [None None 0 1 1]
 [0 1 None 1 1]]
[[1 0 0 0 0]
 [0 1 0 None 1]
 [0 1 None None 1]
 [None None 0 1 1]
 [0 1 0 1 1]]


Enter row (0 to 4):  3
Enter column (0 to 4):  2


This cell is already taken. Try a different cell.


Enter row (0 to 4):  3
Enter column (0 to 4):  1


[[1 0 0 0 0]
 [0 1 0 None 1]
 [0 1 None None 1]
 [None 1 0 1 1]
 [0 1 0 1 1]]
[[1 0 0 0 0]
 [0 1 0 None 1]
 [0 1 None None 1]
 [0 1 0 1 1]
 [0 1 0 1 1]]


Enter row (0 to 4):  2
Enter column (0 to 4):  3


[[1 0 0 0 0]
 [0 1 0 None 1]
 [0 1 None 1 1]
 [0 1 0 1 1]
 [0 1 0 1 1]]
[[1 0 0 0 0]
 [0 1 0 None 1]
 [0 1 0 1 1]
 [0 1 0 1 1]
 [0 1 0 1 1]]


Enter row (0 to 4):  1
Enter column (0 to 4):  3


[[1 0 0 0 0]
 [0 1 0 1 1]
 [0 1 0 1 1]
 [0 1 0 1 1]
 [0 1 0 1 1]]
Determinant is 0: 0 wins!


This code ask AI to generate 1000 times random game, following our strategy. The result alines with our conjecture, the determinant must be zero. We will always win the game!

In [6]:
class StrategicDeterminantGameAuto:
    def __init__(self):
        self.board = np.full((5, 5), None)  # Initialize a 4x4 board with None

    def make_move(self, row, col, player):
        if self.board[row][col] is None:  # Check if the cell is empty
            self.board[row][col] = player
            return True
        return False

    def check_full(self):
        # Check if the board is full
        return not np.any(self.board == None)

    def calculate_determinant(self):
        # Prepare the board for determinant calculation
        numeric_board = np.where(self.board == None, 0, self.board).astype(int)
        return np.linalg.det(numeric_board)

    def player_move_strategy(self):
        # Place 1s in the board following a predefined strategy
        for i in range(5):
            for j in range(5):
                if self.board[i][j] is None:
                    self.make_move(i, j, 1)  # Player 1 makes a move
                    return i, j  # Return the position where 1 was placed

    def ai_move_strategy(self, row, col):
        # AI places 0s strategically next to 1s according to the given rules
        if col in [0, 2]:  # If 1 is in column 0 or 2, place 0 in the next column
            target_col = col + 1
        else:  # If 1 is in column 1 or 3, place 0 in the previous column
            target_col = col - 1
        
        # Find the first empty cell in the target column
        for i in range(5):
            if self.board[i][target_col] is None:
                self.make_move(i, target_col, 0)  # AI places 0
                return

    def play(self):
        while not self.check_full():
            row, col = self.player_move_strategy()
            if self.check_full():
                break
            self.ai_move_strategy(row, col)

        # Return the determinant to decide the winner
        return self.calculate_determinant()

# Play the game 100 times and count the number of times determinant is 0
determinant_zero_count = 0
for _ in range(1000):
    game = StrategicDeterminantGameAuto()
    det = game.play()
    if det == 0:
        determinant_zero_count += 1

determinant_zero_count


1000